### ISSUE TITLE
m2html should be in main at repository rather than in atdocs repository

### ISSUE THREAD

**Issue by bnash** [atcollab/atdoc#1]

**Comment by lnadolski** [comment]
Let me know when this is done. 
Just give the directory. I am make at function to generate all the documentation.
I also work to put the doc online using Git webpages
Laurent.

**Comment by bnash** [comment]
I wrote this issue wrong.  I think we decided that the m2html should be in the main at repository, since it is generated directly from the files in that repository.

I generated the m2html files again and added it to the main repository here
https://github.com/atcollab/at/tree/master/docs/m2html

I should have created a pull request before committing... I'll try to do that in the future.
